ALTER SESSION SET CURRENT_SCHEMA = EBTAPP;
-- As part of phase four all the merchant flows will be showcased here

SELECT * FROM VIEW_TRANSACTIONS;
SELECT * FROM VIEW_TRANSACTIONITEMLIST;
SELECT * FROM VIEW_MERCHANT;
SELECT * FROM MERCHANT_TRANSACTION_DETAILS;