--EBT ADMIN ANALYSIS REPORT -- should be run in EBT APP
ALTER SESSION SET CURRENT_SCHEMA = EBTAPP;
SET SERVEROUTPUT ON


SELECT * FROM ITEM_QTY_VS_AMOUNT_VIEW;

SELECT * FROM CUST_FOOD_VS_CASH_VIEW;

SELECT * FROM transaction_summary_view;

SELECT * FROM age_view;

SELECT * FROM card_status_counts;

SELECT * FROM COUNT_SUCCESS_FAIL_TRANSACTION_VIEW;
