SET SERVEROUTPUT ON
BEGIN
	FOR I IN(
		WITH MY_USERS AS(
			SELECT 'EBTMERCHANT' UNAME FROM DUAL
			UNION ALL
			SELECT 'EBTUSER' FROM DUAL
			UNION ALL
			SELECT 'EBTADMIN' FROM DUAL
		)
		SELECT MU.UNAME
		FROM MY_USERS MU
		INNER JOIN ALL_USERS AU
		ON AU.USERNAME = MU.UNAME
	)
	LOOP
		DBMS_OUTPUT.PUT_LINE('User to be dropped: '||I.UNAME);
		EXECUTE IMMEDIATE 'DROP USER '||I.UNAME;
	END LOOP;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/

create user EBTADMIN identified by DataKnicks2023ADMIN;
create user EBTMERCHANT identified by DataKnicks2023MERCH;
create user EBTUSER identified by DataKnicks2023USER;

GRANT SELECT ON VIEW_TRANSACTIONS TO EBTMERCHANT, EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_TRANSACTIONITEMLIST TO EBTMERCHANT, EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_MERCHANT TO EBTMERCHANT, EBTADMIN;

GRANT UPDATE, INSERT ON EBTAPP.USERS TO EBTUSER;
GRANT SELECT ON VIEW_USERS TO EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_EBTCARD TO EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_EBTACCOUNT TO EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_ITEM TO EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_EBTAPPLICATION TO EBTUSER, EBTADMIN;
GRANT SELECT ON VIEW_EBTSCHEDULE TO EBTUSER, EBTADMIN;

GRANT SELECT ON VIEW_ADMIN TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.USERS TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.EBTCARD TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.EBTACCOUNT TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.ADMIN TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.EBTAPPLICATION TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.EBTSCHEDULE TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.ITEM TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.MERCHANT TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.TRANSACTIONITEMLIST TO EBTADMIN;
GRANT INSERT, UPDATE, DELETE ON EBTAPP.TRANSACTIONS TO EBTADMIN;